const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const algorithms=require('../assets/learning-algorithms.js'),management=require('../assets/management-core.js');
function catalog(){const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/projects.js'),'utf8'),context);return JSON.parse(JSON.stringify(context.window.MINI_PROJECTS))}
function inline(slug,globals={}){const html=fs.readFileSync(path.join(__dirname,'..',slug,'index.html'),'utf8');const code=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!m[1].includes('src=')).map(m=>m[2]).join('\n');const context={...globals};vm.createContext(context);vm.runInContext(code.replace(/\bshowStats\(\);/g,''),context);return context}
test('catalogue has 100 unique paths and 73 demos',()=>{const items=catalog();assert.equal(items.length,100);assert.equal(new Set(items.map(p=>p.slug)).size,100);assert.equal(items.filter(p=>p.status==='demo').length,73);assert.equal(items.filter(p=>p.status==='planned').length,27)});
test('gallery search, status, categories and sorting',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/gallery.js'),'utf8'),context);const filter=context.window.PROJECT_GALLERY.filterProjects,items=catalog();assert.equal(filter(items,{query:'fibonacci'})[0].id,11);assert.equal(filter(items,{status:'planned'}).length,27);assert.equal(filter(items,{category:'Management apps',status:'demo'}).length,3);const sorted=filter(items,{sort:'name'});assert.equal(sorted[0].title,[...items].sort((a,b)=>a.title.localeCompare(b.title))[0].title);assert.equal(filter(items,{query:'no-such-project-zz'}).length,0)});
for(const kind of ['bubble','selection','insertion','merge','quick'])test(kind+' trace sorts inputs without mutating them',()=>{for(const values of [[3,1,2],[1],[5,2,5,-1,0],[1,2,3],[3,2,1]]){const before=[...values],trace=algorithms.sorting(kind,values);assert.deepEqual(trace.at(-1).values,[...values].sort((a,b)=>a-b));assert.deepEqual(values,before);assert.ok(trace.length)}});
test('trace input limits and invalid numbers',()=>{assert.deepEqual(algorithms.numbers('1, -2 3.5'),[1,-2,3.5]);for(const value of ['', 'NaN','Infinity','1,x',Array(21).fill(1).join(',')])assert.throws(()=>algorithms.numbers(value))});
test('tree traces maintain BST, AVL and heap behavior',()=>{assert.deepEqual(algorithms.tree('bst',[5,2,9]).at(-1).values,['root: 5','root.L: 2','root.R: 9']);assert.deepEqual(algorithms.tree('avl',[3,2,1]).at(-1).values,['root: 2','root.L: 1','root.R: 3']);for(const values of [[3,1,2],[5,9,0,-2,8]]){const heap=algorithms.tree('heap',values).at(-1).values;for(let i=1;i<heap.length;i++)assert.ok(heap[Math.floor((i-1)/2)]>=heap[i])}});
test('fixed graph traversals and shortest distances',()=>{assert.deepEqual(algorithms.traversal('dfs','A').at(-1).values,['A','B','D','E','C','F']);assert.deepEqual(algorithms.traversal('bfs','A').at(-1).values,['A','B','C','D','E','F']);assert.deepEqual(algorithms.dijkstra('A').at(-1).values,['A: 0','B: 3','C: 2','D: 8','E: 10']);assert.throws(()=>algorithms.traversal('dfs','Z'));assert.throws(()=>algorithms.dijkstra('F'))});
for(const kind of ['kruskal','prim'])test(kind+' spanning tree weight',()=>{const trace=algorithms.mst(kind),accepted=trace.filter(s=>s.message.startsWith('Accept'));assert.equal(accepted.length,5);assert.match(accepted.at(-1).message,/weight 13$/)});
test('management add, edit, duplicate, validation and search',()=>{let records=management.upsert('student',[],{id:'101',name:'Jay',course:'CS'});assert.equal(records.length,1);assert.throws(()=>management.upsert('student',records,{id:'101',name:'Other',course:'CS'}));records=management.upsert('student',records,{id:'102',name:'Updated',course:'Science'},'101');assert.equal(records[0].id,'102');assert.equal(management.search(records,'SCIENCE').length,1);assert.throws(()=>management.normalize('student',{id:'x',name:'',course:'CS'}));assert.throws(()=>management.restore('student','{}'));assert.throws(()=>management.restore('student',JSON.stringify([...records,...records])));assert.deepEqual(management.restore('student',JSON.stringify(records)),records)});
test('library prevents double loans and records returns',()=>{const books=[management.normalize('library',{id:'B1',title:'Book',author:'Writer'})];const loan=management.loan(books,'B1','Jay');assert.equal(loan[0].borrower,'Jay');assert.equal(books[0].borrower,'');assert.throws(()=>management.loan(loan,'B1','Other'));assert.throws(()=>management.loan(books,'B1',''));assert.equal(management.returnBook(loan,'B1')[0].borrower,'')});
test('inventory accepts zero and rejects negative/fractional stock',()=>{assert.equal(management.normalize('inventory',{id:'I1',name:'Item',quantity:0,price:0}).quantity,0);for(const quantity of [-1,1.5,Infinity,1000001])assert.throws(()=>management.normalize('inventory',{id:'I1',name:'Item',quantity,price:1}));assert.throws(()=>management.normalize('inventory',{id:'I1',name:'Item',quantity:1,price:-1}))});
test('array statistics numerical examples and errors',()=>{const stats=inline('25-array-statistics').calculateStats;const value=JSON.parse(JSON.stringify(stats('1,2,3,4')));assert.deepEqual(value,{Count:4,Sum:10,Minimum:1,Maximum:4,Mean:2.5,Median:2.5});assert.equal(stats('-5,0,5').Median,0);for(const input of ['', '1,bad','Infinity',Array(10001).fill(1).join(',')])assert.throws(()=>stats(input))});
test('Caesar handles zero, negative shifts and Unicode text',()=>{const caesar=inline('38-caesar-cipher').caesar;assert.equal(caesar('Abc!',0),'Abc!');assert.equal(caesar('Abc!',-1),'Zab!');assert.equal(caesar(caesar('Hello 🌍',53),53,true),'Hello 🌍');assert.throws(()=>caesar('A',1.5))});
test('Base64 round trip handles Unicode and invalid data',()=>{const api=inline('39-text-encryption',{TextEncoder,TextDecoder,Uint8Array,btoa,atob});for(const input of ['','Hello','नमस्ते 🌍'])assert.equal(api.decodeBase64(api.encodeBase64(input)),input);assert.throws(()=>api.decodeBase64('%%%'))});
test('structured run encoding supports long runs, digits and emoji',()=>{const api=inline('72-file-compression');for(const input of ['', 'AAAAAAAAAAAA','111122','🌍🌍a'])assert.equal(api.decodeRuns(api.encodeRuns(input)),input);for(const input of ['{}','[["a",-1]]','[["ab",2]]','[["a",1000001]]'])assert.throws(()=>api.decodeRuns(input))});
